### ISSUE TITLE
Block判断martet

### ISSUE THREAD

**Issue by Chunmi-Tommy3886** [fasiondog/hikyuu#103]
market_code='SH600605'
blocka[market_code] 这样是可以的
但是文档上
market_code='sh600605'
blocka[market_code] 这样是不可以

**Comment by fasiondog** [comment]
![图片](https://github.com/fasiondog/hikyuu/assets/1145161/eb34e1c8-f8fe-44ab-a3b2-f7fcedeab27d)
我这并不会，可能我用的最新的代码吧
