### ISSUE TITLE
现在读取不到财务数据了,返回[]

### ISSUE THREAD

**Issue by hoooou** [fasiondog/hikyuu#105]
finance=s.get_finance_info()

**Comment by fasiondog** [comment]
我这好像可以的，要hikyuutdx先下载
![图片](https://github.com/fasiondog/hikyuu/assets/1145161/e37bdbfb-a251-4c28-9241-2728d0dc6995)

**Comment by hoooou** [comment]
从代码上看，往db导入数据的代码引用都被注掉了呀，权息数据是有的，但stock.db里面的stkfinance这个表是空的
<img width="750" alt="image" src="https://github.com/fasiondog/hikyuu/assets/9627034/91503e3e-033b-468a-aa35-2726b03b34ff">
<img width="1023" alt="image" src="https://github.com/fasiondog/hikyuu/assets/9627034/2c5945a2-96c0-4e34-a094-cd6a501b8fe5">

**Comment by hoooou** [comment]
@@@@我手动调用了这部分代码，stkfinance表才补全了
<img width="746" alt="image" src="https://github.com/fasiondog/hikyuu/assets/9627034/f4aeab64-6a33-4870-9ec0-985f38839fa3">

**Comment by hoooou** [comment]
@fasiondog 我手动调用了这部分代码，才补全了stkfinance
<img width="746" alt="image" src="https://github.com/fasiondog/hikyuu/assets/9627034/ee80bee9-c746-4f91-8802-9bef22f724f8">

**Comment by fasiondog** [comment]
现在没有用表来读取财务数据了，直接用的下载的财务数据文件

**Comment by fasiondog** [comment]
你这个是不是用的比较老的版本

**Comment by kbugstar** [comment]
@fasiondog 我试了一下，hikyuu版本是 hikyuu_1.2.7_202307160109_x64_release
sm['sz000001'].get_history_finance_info(D(20230331)) 是使用的download下的gpcw财务文件，不过会报
2023-09-21 02:05:17.641 [HKU-W] - Over MAX_COL_NUM! F:/stocks/downloads/finance/gpcw20230331.dat (HistoryFinanceReader.cpp:69) 这个警告
sm['sz000001'].get_finance_info()这个api使用的是stock.db数据中stkfinance表里的数据，如果没有下载，返回[]

**Comment by kbugstar** [comment]
> @fasiondog 奇怪，sm['sz300750'].get_finance_info() sm['sh688981'].get_finance_info() 创业和科创都无法返回数据，在stock.db数据库stkfinance表中都有相应的数据, get_history_finance_info()函数也有类似的问题 而沪深主板的票都可以获得返回数据, 看了一下源代码，没找到原因

Parameter Stock::getFinanceInfo() const {
    Parameter result;
    HKU_IF_RETURN(type() != STOCKTYPE_A, result);

    BaseInfoDriverPtr driver = StockManager::instance().getBaseInfoDriver();
    if (driver) {
        result = driver->getFinanceInfo(market(), code());
    }

    return result;
}
大概问题在HKU_IF_RETURN(type() != STOCKTYPE_A, result);这个判断，
需要修改成HKU_IF_RETURN(type() != STOCKTYPE_A && type() != STOCKTYPE_GEM && type() != STOCKTYPE_START,
              result);

**Comment by fasiondog** [comment]
好的，3Q，如果可以的话，你可以试着直接改了提交PR

**Comment by kbugstar** [comment]
@fasiondog 提交了

**Comment by fasiondog** [comment]
> @fasiondog 我手动调用了这部分代码，才补全了stkfinance <img alt="image" width="746" src="https://user-images.githubusercontent.com/9627034/266184709-ee80bee9-c746-4f91-8802-9bef22f724f8.png">

仔细看了下，你是对的，应该是有一段时间 pytdx（有些服务器） 经常下载不了财务数据，调整时忘了。后面补上。
