### ISSUE TITLE
有没有办法直接获得市场指定日期的一个切片呢？

### ISSUE THREAD

**Issue by kbugstar** [fasiondog/hikyuu#109]
比如现在如果想获得blocka所包含的所有股票当天的K线数据，用来获得成交量排名，涨幅排名之类的数据，
只能对blocka进行遍历，使用get_kdata(Q(-1))来获得一条k线数据，再concat成一个包含所有代码的dataframe,
有没有一个方法可以比较快的获取整个市场或者板块包含代码的日K数据？

**Comment by fasiondog** [comment]
这个暂时没有，只能自己先封个函数拼装下

**Comment by kbugstar** [comment]
> 这个暂时没有，只能自己先封个函数拼装下

嗯嗯，了解

**Comment by fasiondog** [comment]
现在可以用 concat_to_df
    示例:
        query = Query(-200)
        k_list = [stk.get_kdata(query) for stk in [sm['sz000001'], sm['sz000002']]]
        ma_list = [MA(k) for k in k_list]
        concat_to_df(sm.get_trading_calendar(query), ma_list, head_stock_code=True, head_ind_name=False)

    输出：
                date	SZ000001	SZ000002
        0	2023-05-12 00:00:00	12.620000	15.060000
        1	2023-05-15 00:00:00	12.725000	15.060000
        2	2023-05-16 00:00:00	12.690000	15.010000
        3	2023-05-17 00:00:00	12.640000	14.952500
        4	2023-05-18 00:00:00	12.610000	14.886000
        ...	...	...	...
        195	2024-03-01 00:00:00	9.950455	9.837273
        196	2024-03-04 00:00:00	9.995909	9.838182
        197	2024-03-05 00:00:00	10.038182	9.816364
        198	2024-03-06 00:00:00	10.070455	9.776818
        199	2024-03-07 00:00:00	10.101364	9.738182
