### ISSUE TITLE
version 1.14.2, shared lib is ok, but static lib raises error H5::PredType::NATIVE_UINT64 <struct at NULL>

### ISSUE THREAD

**Issue by liyqxtu** [fasiondog/hikyuu#111]
![1](https://github.com/fasiondog/hikyuu/assets/4734699/30c85931-b973-46bd-b018-cc1d44938d6f)

**Comment by fasiondog** [comment]
我没提供 windows 1.14.2 的 hdf5 版本，只有 1.12.2

**Comment by liyqxtu** [comment]
yeah, i raise a issue for hdf5 project at the same time.  https://github.com/HDFGroup/hdf5/issues/3544

static GlobalInitializer s_global_initializer;  // raise error H5::PredType::NATIVE_UINT64 <struct at NULL>

**Comment by fasiondog** [comment]
这个不是 hdf5 的问题，GlobalInitializer 用来控制全局静态变量的初始化顺序，决定了不能用 hdf5 静态库，无法控制它的静态变量初始化

**Comment by liyqxtu** [comment]
如果硬是要使用hdf5静态库的话，应该如何修改源码呢？是修改hdf5的源码，还是本库的源码呢？能否提供一些思路，先谢谢啦

**Comment by fasiondog** [comment]
自己根据GlobalInitializer 重写初始化和退出函数，分别在启动前和退出时调用
