### ISSUE TITLE
ADVANCE指标问题

### ISSUE THREAD

**Issue by kbugstar** [fasiondog/hikyuu#115]
在使用ADVANCE指标时，不管如何改变参数获得的结果都不正常
In [2]: a = ADVANCE(Q(-5))

In [3]: list(a)
Out[3]: [nan, 1694.0, 1694.0, nan, 1694.0]
经过调试，问题在IndicatorImp.cpp下面的函数的中
```
void IndicatorImp::setContext(const Stock &stock, const KQuery &query) {
    KData kdata = getContext();
    if (kdata.getStock() == stock || kdata.getQuery() == query) {
        if (m_need_calculate) {
            calculate();
        }
        return;
    }

    m_need_calculate = true;

    // 子节点设置上下文
    if (m_left)
        m_left->setContext(stock, query);
    if (m_right)
        m_right->setContext(stock, query);
    if (m_three)
        m_three->setContext(stock, query);

    // 如果上下文有变化则重设上下文
    setParam<KData>("kdata", stock.getKData(query));

    // 启动重新计算
    calculate();
}
```
在使用ADVANCE指标时，kdata.getQuery() == query这个条件永远为真，所以
ADVANCE指标的calculate函数在第一次setContext后，不会再设置成其它stock的context
造成这个函数的结果异常

如何将条件语句改成kdata.getStock() == stock && kdata.getQuery() == query，ADVANCE指标可以获得正确的结果，
但是不知道修改这个函数会有什么样的副作用，无法确定是否可以修改

**Comment by fasiondog** [comment]
![图片](https://github.com/fasiondog/hikyuu/assets/1145161/f364973d-ad60-4cda-aaa7-9155f15d7edf)
你试下 ignore_context 参数

**Comment by kbugstar** [comment]
> ![图片](https://user-images.githubusercontent.com/1145161/270401505-f364973d-ad60-4cda-aaa7-9155f15d7edf.png) 你试下 ignore_context 参数

在前面试过这个参数，没有作用，原因上面说了

**Comment by fasiondog** [comment]
那应该就是BUG，需要改成 &&，原意是没变化不计算。可以的话，欢迎提交 PR ：）

**Comment by kbugstar** [comment]
@fasiondog 已提交PR
