### ISSUE TITLE
xmake过程报错，另 python版本应使用哪个版本

### ISSUE THREAD

**Issue by oOTnTOo** [fasiondog/hikyuu#12]
Xmake报错：
error: C:\Program Files (x86)\xmake/core/base/os.lua:691: C:\Program Files (x86)\xmake/core/base/os.lua:691: F:\Workspace\Quant\hikyuu\hikyuu_pywrap\xmake.lua:22: attempt to call global 'get_config' (a nil value)
stack traceback:
    [F:\Workspace\Quant\hikyuu\hikyuu_pywrap\xmake.lua:22]: in main chunk

stack traceback:
    [C]: in function 'error'
    [C:\Program Files (x86)\xmake/core/base/os.lua:691]: in function 'raise'
    [C:\Program Files (x86)\xmake/core/base/interpreter.lua:1593]: in function 'add_subdirs'
    [F:\Workspace\Quant\hikyuu\xmake.lua:79]: in main chunk
--with-python编译报
libs\python\src\exec.cpp(112): error C3861: “_Py_fopen”: 找不到标识符

求解……

**Comment by waruqi** [comment]
装下v2.2.2-dev版本，https://github.com/tboox/xmake/releases/download/v2.2.1/xmake-v2.2.2-dev.exe

**Comment by fasiondog** [comment]
是的，要用xmake 2.2.2（目前还没正式发布）。python只支持3.X。

**Comment by oOTnTOo** [comment]
> 是的，要用xmake 2.2.2（目前还没正式发布）。python只支持3.X。

我使用的python3.1和3.7，3.7直接报找不到python，3.1找到了，但是报
libs\python\src\exec.cpp(112): error C3861: “_Py_fopen”: 找不到标识符
请问大佬怎么解？

**Comment by oOTnTOo** [comment]
> 是的，要用xmake 2.2.2（目前还没正式发布）。python只支持3.X。

还有个问题，C++开发也必须要boost::python吗？

**Comment by oOTnTOo** [comment]
> 装下v2.2.2-dev版本，https://github.com/tboox/xmake/releases/download/v2.2.1/xmake-v2.2.2-dev.exe

谢谢，我卸载了原有的xmake换成了您给的地址。但是出现新的错误……
![image](https://user-images.githubusercontent.com/31060590/45858068-39f28180-bd8e-11e8-8b26-ac7b4f2eb454.png)
这个……您知道是怎么回事儿吗？

**Comment by waruqi** [comment]
可以执行下：`xmake -v --backtrace` 后看下输出，或者先尝试执行下：`xmake f -c` 清下之前的缓存配置后，再执行下`xmake`编译试试

**Comment by waruqi** [comment]
https://github.com/fasiondog/hikyuu/blob/master/hikyuu_pywrap/xmake_on_load.lua里面执行`        local pydir = os.iorun("python -c \"import sys; print(sys.executable)\"")
`出错了。。你装python了没？

**Comment by fasiondog** [comment]
要用到boost.python。boost的编译你参考下travis.yml里的，boost.python比较麻烦，编译完了要检查下stage/lib下是否有相应的boost_python版本的动态库生成。如果和使用的python不一致，后面会出错。

**Comment by oOTnTOo** [comment]
> [https://github.com/fasiondog/hikyuu/blob/master/hikyuu_pywrap/xmake_on_load.lua里面执行`](https://github.com/fasiondog/hikyuu/blob/master/hikyuu_pywrap/xmake_on_load.lua%E9%87%8C%E9%9D%A2%E6%89%A7%E8%A1%8C%60) local pydir = os.iorun("python -c "import sys; print(sys.executable)"")
> `出错了。。你装python了没？

装了，3.7-32bit，不过好像它在安装过程中没有设置，PATH变量……

![image](https://user-images.githubusercontent.com/31060590/45859426-d881e100-bd94-11e8-9fcb-3fc2b858bb16.png)

**Comment by fasiondog** [comment]
当然要装python，并且路径里能找到

**Comment by waruqi** [comment]
我更新了下xmake，对python的查找内置支持了，即使win上没有设置path变量，https://github.com/fasiondog/hikyuu/issues/13
