### ISSUE TITLE
ICval实现导致vector越界

### ISSUE THREAD

**Issue by yangrq1018** [fasiondog/hikyuu#128]
ICval实现里这段

```cpp
void ICval::_calculate(const Indicator& data) {
    double value = getParam<double>("value");
    int discard = getParam<int>("discard");

    size_t total = 0;
    if (isLeaf()) {
        //叶子节点
        KData k = getContext();
        // if (k.getStock().isNull()) {
        //     _readyBuffer(1, 1);
        //     if (discard < 1) {
        //         m_discard = 0;
        //         _set(value, 0, 0);
        //     } else {
        //         m_discard = 1;
        //     }
        //     return;
        // }

        total = k.size();
        if (0 == total) {
            return;
        }

        _readyBuffer(total, 1);

    } else {
        //非叶子节点
        total = data.size();
        discard = data.discard() > discard ? data.discard() : discard;
    }

    m_discard = discard > total ? total : discard;

    for (size_t i = m_discard; i < total; ++i) {
        _set(value, i, 0);
    }
}
```
被comment掉的这块代码，对叶子节点的特殊处理，会导致`IndicatorImp::alike`里因为未检查长度导致vector越界。

举个例子
```cpp
Indicator RSI(int n = 14) {
    Indicator diff = REF(0) - REF(1);
    Indicator u = IF(diff > 0, diff, 0);
    Indicator d = IF(diff < 0, (-1) * diff, 0);
    Indicator ema_u = EMA(u, n);
    Indicator ema_d = EMA(d, n);
    ema_d = IF(ema_d == 0.0, 1, ema_d);
    Indicator rs = ema_u / ema_d;
    Indicator _1 = CVAL(1);
    Indicator rsi = (_1 - _1 / (_1 + rs)) * CVAL(100);
    rsi.name("RSI");
    rsi.setParam<int>("n", n);
    return rsi;
}
```
因为里面混合了非叶子节点(OP）的CVAL算子和叶子节点CVAL算子，其buffer长度不一致

我不太清楚这块为什么要这样写，我comment掉之后好像也能运行，想问下这个怎么改比较好。

**Comment by fasiondog** [comment]
CVAL比较特殊，你试下像下面这样加上第二个HKU_IF_RETURN, 如果名称是CVAL直接返回 false 试下

```cpp
bool IndicatorImp::alike(const IndicatorImp &other) const {
    HKU_IF_RETURN(this == &other, true);
    HKU_IF_RETURN(m_name == "CVAL" || other.name() == "CVAL", false);
    HKU_IF_RETURN(m_optype != other.m_optype || typeid(*this).name() != typeid(other).name() ||
                    m_params != other.m_params || m_discard != other.m_discard ||
                    m_result_num != other.m_result_num ||
                    m_ind_params.size() != other.m_ind_params.size(),
                  false);
```

**Comment by fasiondog** [comment]
> ICval实现里这段
> 
> ```c++
> void ICval::_calculate(const Indicator& data) {
>     double value = getParam<double>("value");
>     int discard = getParam<int>("discard");
> 
>     size_t total = 0;
>     if (isLeaf()) {
>         //叶子节点
>         KData k = getContext();
>         // if (k.getStock().isNull()) {
>         //     _readyBuffer(1, 1);
>         //     if (discard < 1) {
>         //         m_discard = 0;
>         //         _set(value, 0, 0);
>         //     } else {
>         //         m_discard = 1;
>         //     }
>         //     return;
>         // }
> 
>         total = k.size();
>         if (0 == total) {
>             return;
>         }
> 
>         _readyBuffer(total, 1);
> 
>     } else {
>         //非叶子节点
>         total = data.size();
>         discard = data.discard() > discard ? data.discard() : discard;
>     }
> 
>     m_discard = discard > total ? total : discard;
> 
>     for (size_t i = m_discard; i < total; ++i) {
>         _set(value, i, 0);
>     }
> }
> ```
> 
> 被comment掉的这块代码，对叶子节点的特殊处理，会导致`IndicatorImp::alike`里因为未检查长度导致vector越界。
> 
> 举个例子
> 
> ```c++
> Indicator RSI(int n = 14) {
>     Indicator diff = REF(0) - REF(1);
>     Indicator u = IF(diff > 0, diff, 0);
>     Indicator d = IF(diff < 0, (-1) * diff, 0);
>     Indicator ema_u = EMA(u, n);
>     Indicator ema_d = EMA(d, n);
>     ema_d = IF(ema_d == 0.0, 1, ema_d);
>     Indicator rs = ema_u / ema_d;
>     Indicator _1 = CVAL(1);
>     Indicator rsi = (_1 - _1 / (_1 + rs)) * CVAL(100);
>     rsi.name("RSI");
>     rsi.setParam<int>("n", n);
>     return rsi;
> }
> ```
> 
> 因为里面混合了非叶子节点(OP）的CVAL算子和叶子节点CVAL算子，其buffer长度不一致
> 
> 我不太清楚这块为什么要这样写，我comment掉之后好像也能运行，想问下这个怎么改比较好。

如果上面可行的话，说一声，或者直接帮忙 PR 了
