### ISSUE TITLE
建议增加一个简化版的绩效统计

### ISSUE THREAD

**Issue by szit2023** [fasiondog/hikyuu#139]
建议增加一个简化版的绩效统计，包括常见的：
策略收益、年化收益、夏普比率、胜率、盈亏比、最大回撤等指标即可

**Comment by fasiondog** [comment]
https://github.com/fasiondog/hikyuu/pull/185 增加 sys.performance 绘制系统性能，增加sharp比率最大回撤等简化的绩效显示
下一版本发布

**Comment by fasiondog** [comment]
2.0.0 已增加 sys.performance 直接生成绩效图表
![图片](https://github.com/fasiondog/hikyuu/assets/1145161/79e5b888-b4b1-4f25-98fb-7f6615c3a757)
