### ISSUE TITLE
mangled name for boost::python::detail::caller<F, CallPolicies, Sig>::caller(F, CallPolicies)

### ISSUE THREAD

**Issue by guyansrg** [fasiondog/hikyuu#17]
1. build environment:
Ubuntu: 18.04.1
hikyuu: 1.0.9
xmake: 2.2.2
g++: 7.3.0
python: 3.6.6
boost: 1.67.0
※ 按照 [C++ 开发者指南](https://hikyuu.readthedocs.io/en/latest/developer.html) 文档来编译的。

2. error message:
<pre>
[21%]: compiling.release hikyuu_pywrap/trade_sys/_AllocateFunds.cpp
[22%]: compiling.release hikyuu_pywrap/trade_sys/_System.cpp
[24%]: compiling.release hikyuu_pywrap/trade_sys/_Selector.cpp
[26%]: compiling.release hikyuu_pywrap/trade_sys/_Condition.cpp
error: /home/puppy/workspace/Hikyuu/boost_1_67_0/boost/python/detail/caller.hpp:174:5: error: mangled name for ‘boost::python::detail::caller<F, CallPolicies, Sig>::caller(F, CallPolicies) [with F = long unsigned int (std::vector<hku::SystemWeight>::*)() const noexcept; CallPolicies = boost::python::default_call_policies; Sig = boost::mpl::vector2<long unsigned int, std::vector<hku::SystemWeight>&>]’ will change in C++17 because the exception specification is part of a function type [-Werror=noexcept-type]
     caller(F f, CallPolicies p) : base(f,p) {}
     ^~~~~~
/home/puppy/workspace/Hikyuu/boost_1_67_0/boost/python/detail/caller.hpp:174:5: error: mangled name for ‘boost::python::detail::caller<F, CallPolicies, Sig>::caller(F, CallPolicies) [with F = long unsigned int (std::vector<hku::SystemWeight>::*)() const noexcept; CallPolicies = boost::python::default_call_policies; Sig = boost::mpl::vector2<long unsigned int, std::vector<hku::SystemWeight>&>]’ will change in C++17 because the exception specification is part of a function type [-Werror=noexcept-type]
In file included from /home/puppy/workspace/Hikyuu/boost_1_67_0/boost/python/object/function_handle.hpp:10:0,
                 from /home/puppy/workspace/Hikyuu/boost_1_67_0/boost/python/converter/arg_to_python.hpp:19,
                 from /home/puppy/workspace/Hikyuu/boost_1_67_0/boost/python/call.hpp:15,
                 from /home/puppy/workspace/Hikyuu/boost_1_67_0/boost/python/object_core.hpp:14,
                 from /home/puppy/workspace/Hikyuu/boost_1_67_0/boost/python/args.hpp:22,
                 from /home/puppy/workspace/Hikyuu/boost_1_67_0/boost/python.hpp:11,
                 from hikyuu_pywrap/trade_sys/_AllocateFunds.cpp:8:
/home/puppy/workspace/Hikyuu/boost_1_67_0/boost/python/object/py_function.hpp: In instantiation of ‘boost::python::objects::py_function::py_function(const Caller&) [with Caller = boost::python::detail::caller<long unsigned int (std::vector<hku::SystemWeight>::*)() const noexcept, boost::python::default_call_policies, boost::mpl::vector2<long unsigned int, std::vector<hku::SystemWeight>&> >]’:
/home/puppy/workspace/Hikyuu/boost_1_67_0/boost/python/make_function.hpp:60:38:   required from ‘boost::python::api::object boost::python::detail::make_function_aux(F, const CallPolicies&, const Sig&, const keyword_range&, NumKeywords) [with F = long unsigned int (std::vector<hku::SystemWeight>::*)() const noexcept; CallPolicies = boost::python::default_call_policies; Sig = boost::mpl::vector2<long unsigned int, std::vector<hku::SystemWeight>&>; NumKeywords = mpl_::int_<0>; boost::python::detail::keyword_range = std::pair<const boost::python::detail::keyword*, const boost::python::detail::keyword*>]’
/home/puppy/workspace/Hikyuu/boost_1_67_0/boost/python/make_function.hpp:140:37:   required from ‘boost::python::api::object boost::python::make_function(F, const CallPolicies&, const Keywords&, const Signature&) [with F = long unsigned int (std::vector<hku::SystemWeight>::*)() const noexcept; CallPolicies = boost::python::default_call_policies; Keywords = boost::python::detail::keywords<0>; Signature = boost::mpl::vector2<long unsigned int, std::vector<hku::SystemWeight>&>]’
/home/puppy/workspace/Hikyuu/boost_1_67_0/boost/python/class.hpp:493:26:   required from ‘void boost::python::class_<T, X1, X2, X3>::def_impl(T*, const char*, Fn, const Helper&, ...) [with T = std::vector<hku::SystemWeight>; Fn = long unsigned int (std::vector<hku::SystemWeight>::*)() const noexcept; Helper = boost::python::detail::def_helper<const char*>; W = std::vector<hku::SystemWeight>; X1 = boost::python::detail::not_specified; X2 = boost::python::detail::not_specified; X3 = boost::python::detail::not_specified]’
/home/puppy/workspace/Hikyuu/boost_1_67_0/boost/python/class.hpp:231:9:   required from ‘boost::python::class_<T, X1, X2, X3>::self& boost::python::class_<T, X1, X2, X3>::def(const char*, F) [with F = long unsigned int (std::vector<hku::SystemWeight>::*)() const noexcept; W = std::vector<hku::SystemWeight>; X1 = boost::python::detail::not_specified; X2 = boost::python::detail::not_specified; X3 = boost::python::detail::not_specified; boost::python::class_<T, X1, X2, X3>::self = boost::python::class_<std::vector<hku::SystemWeight> >]’
hikyuu_pywrap/trade_sys/_AllocateFunds.cpp:62:49:   required from here
</pre>

**Comment by fasiondog** [comment]
估计是你的g++版本太低了吧，不支持C++11，至少得4.8以上吧，我这都5.4了

**Comment by guyansrg** [comment]
> 估计是你的g++版本太低了吧，不支持C++11，至少得4.8以上吧，我这都5.4了

不好意思，g++版本号写错了，是7.3.0

**Comment by fasiondog** [comment]
那错误看起来像是版本太高产生的告警，你把根目录的xmake.lua里的第8行注释掉，第9行打开，告警继续编译。

**Comment by guyansrg** [comment]
> 那错误看起来像是版本太高产生的告警，你把根目录的xmake.lua里的第8行注释掉，第9行打开，告警继续编译。

按照上面提示修改后，无警告编译通过。
