### ISSUE TITLE
采用mingw编译有问题

### ISSUE THREAD

**Issue by derek2019** [fasiondog/hikyuu#19]
采用xmake编译时，提示
checking for the vswhere.exe ... no
checking for the vswhere ... no
checking for the microsoft visual studio(x64)version ... no

后面找xmake兄弟确认，说交叉编译需要用xmake f -p mingw --sdk=${GCC_PATH} -a x86_64。确实没有检查visual studio了。但是提示下面错误。
```
stack traceback:
    [C]: in function 'error'
    [F:\xmake/core/base/os.lua:705]: in function 'raise'
    [F:\xmake\core\sandbox\modules\os.lua:352]: in function 'iorun'
    [F:\codes\hikyuu\hikyuu\hikyuu_pywrap\xmake_on_load.lua:29]:
    [C]: in function 'load'
    [F:\xmake/core/project/target.lua:229]: in function '_load'
    [F:\xmake/core/project/project.lua:542]: in function '_load_targets'
    [F:\xmake/core/project/project.lua:705]: in function 'targets'
    [F:\xmake\actions\config\main.lua:128]: in function '_check_target'
    [F:\xmake\actions\config\main.lua:283]:
    [C]: in function 'load'
    [F:\xmake/core/base/task.lua:512]: in function 'run'
    [F:\xmake/core/main.lua:246]:

stack traceback:
    [C]: in function 'error'
    [F:\xmake/core/base/os.lua:705]: in function 'raise'
    [F:\xmake/core/project/project.lua:707]: in function 'targets'
    [F:\xmake\actions\config\main.lua:128]: in function '_check_target'
    [F:\xmake\actions\config\main.lua:283]:
    [C]: in function 'load'
    [F:\xmake/core/base/task.lua:512]: in function 'run'
    [F:\xmake/core/main.lua:246]:
```
我根据前面一个帖子信息说没有安装Python。但是我是已经安装python，并且把python路径设置到path了。
C:\Users\Derek>echo %path%
C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Git\cmd;F:\codes\mingw64\bin;;**F:\xmake;F:\Python\Python37\Scripts\;F:\Python\Python37\;**C:\Users\Derek\AppData\Local\Microsoft\WindowsApps;C:\Users\Derek\AppData\Local\Programs\Microsoft VS Code\bin;F:\xmake;

**Comment by derek2019** [comment]
补充：xmake为2.2.3版本

**Comment by derek2019** [comment]
昨天不小心关了

**Comment by fasiondog** [comment]
装VS了没？用VS的命令行交叉编译

**Comment by derek2019** [comment]
就是没有装VS，所以用mingw。xmake兄弟说可以。现在感觉还没有到实际编译，在检查Python时就出错了。

**Comment by waruqi** [comment]
> 后面提示3个deprected项。大致意思说用add_headerfiles替换add_headers。麻烦专家指导下

这个不用管，因为xmake的 dev分支版本，改进了对头文件的处理，新增了add_headerfiles接口，add_headers接口新版本之后会废弃掉，但是会兼容几个大版本，并不会影响当前的正常编译，仅仅只会加个 Warning提示信息而已，用户可以不用关心浙西提示信息 @derek2019 

@fasiondog 如果有需要可以等xmake新版本发布后，使用add_headerfiles新接口，当然还是用老的接口，依然是可以的，并没有任何影响，新版本是向下兼容的。。

关于这块，可以看下 https://github.com/tboox/xmake/issues/319 和 https://github.com/tboox/xmake/issues/291

**Comment by derek2019** [comment]
@waruqi 感谢回复。
我是根据
这个环境就是出现最上面的问题。

**Comment by waruqi** [comment]
看错误 是 python3-config --includes 执行失败了，你可以手动在 cmd下执行试试，看看是否ok

**Comment by derek2019** [comment]
是像下面这样执行吗？不知道是否少import内容
```
F:\codes\hikyuu\hikyuu>xmake l
> import("lib.detect.find_tool")

{
    main = <function: 0x037bca30>
}
> os.iorun("python3 --version")
F:\xmake/core/base/os.lua:705:
stack traceback:
        [C]: in function 'error'
        F:\xmake/core/base/os.lua:705: in function 'raise'
        F:\xmake\core\sandbox\modules\os.lua:352: in function <F:\xmake\core\sandbox\modules\os.lua:340>
        [C]: in function 'interactive'
        ...ake\core\sandbox\modules\import\core\sandbox\sandbox.lua:64: in function 'interactive'
        F:\xmake\plugins\lua\xmake.lua:90: in function <F:\xmake\plugins\lua\xmake.lua:32>
        [C]: in function 'load'
        F:\xmake/core/base/task.lua:512: in function 'run'
        F:\xmake/core/main.lua:246: in function <F:\xmake/core/main.lua:176>
```

**Comment by waruqi** [comment]
不是，你首先得确保path下直接运行 python3 和python3-config都ok才行，xmake也只不过直接调用运行了这两个命令而已，如果你的python环境没装好，当然这个工程编译不过了

这其实跟xmake本身没啥关系，因为这个项目依赖python3而已，所以首先得确保你装好python3 和 python3-config了

看目前的错误信息，应该是你装完python3后，path环境变量没有加正确导致python3和python3-config直接运行找不到

而python3因为脚本里面用了find_tool python3，找到了绝对路径，所以脚本里面运行正常，但是python3-config 是通过iorun直接调用的，这就需要设置上正确的path路径了

open cmd

```console
$ python3 --version
$ python3-config --includes
```

**Comment by derek2019** [comment]
从这个帖子看，win环境下，只装python3.*版本，是不会有python3这个命令符的。
https://stackoverflow.com/questions/40914108/bash-python3-command-not-found-windows-discord-py

**Comment by derek2019** [comment]
我后面试着再安装一个python2版本，发现先装python3.*，无法再装python2.*版本。

**Comment by derek2019** [comment]
多谢

**Comment by fasiondog** [comment]
加了个“assert(pydir, "python3-config not found!")”，没装mingw，@derek2019 欢迎PR下mingw的编译改动

**Comment by waruqi** [comment]
> 加了个“assert(pydir, "python3-config not found!")”，没装mingw，@derek2019 欢迎PR下mingw的编译改动

os.iorun运行失败，会中断触发错误，执行不到这行，需要加个try-catch

```lua
local pydir = try { function () return os.iorun("python3-config --includes"):trim() end }
assert(pydir, "python3-config not found!")
```
