### ISSUE TITLE
请问建立mysql数据建的脚本在哪？

### ISSUE THREAD

**Issue by markqiu** [fasiondog/hikyuu#2]

**Comment by fasiondog** [comment]
看下帮助，用hku_config配置

**Comment by markqiu** [comment]
你的意思是设置好Mysql的话，表会自动建立？

**Comment by fasiondog** [comment]
你的意思是要用Mysql存数据，我理解错了。不过我没做导入MySql的工具，因为本地用，MySQL没hdf5快，当时只是随便编了个脚本将HDF5的数据导入MySQL，比较下速度和磁盘占用，所以没有配套的数据导入工具。BaseInfo的表和Sqlite的一样，K线数据是按市场建库，每个股票一张表如sh000001

修改配置文件hikyuu_win.ini，类似如下：（注：没有配套的导入数据工具） 
[baseinfo]
type = mysql host = 127.0.0.1 port = 3306 usr = root db = stk_base

[sh_day] type = mysql host = 127.0.0.1 port = 3306 usr = root database = stk_sh_day ;（数据库里的表按sh000001方式命名，一个股票一张表）

**Comment by markqiu** [comment]
知道了，谢谢
