### ISSUE TITLE
每股基本收益第4季度是错误的

### ISSUE THREAD

**Issue by cheunjq** [fasiondog/hikyuu#267]
每股基本收益第4季度是错误的，而且总是等于第3季度的数据，是什么原因吗？

**Comment by fasiondog** [comment]
FINANCE 是会根据日期获取历史财务的，也就是说在财报没有发布之前取的都是最靠近的历史记录。所以，不知道你是不是指的这个，如果不是，需要麻烦更具体一点

**Comment by cheunjq** [comment]
s = sm['sh600527']
e = FINANCE(0)
q = Query(-5, ktype=Query.QUARTER)
k = s.get_kdata(q)
d = k.get_datetime_list()
print(d)
ret = e(k)
for i in ret:
    print(i)

返回：
DatetimeList[2023-06-30 00:00:00, 2023-09-30 00:00:00, 2023-12-31 00:00:00, 2024-03-31 00:00:00, 2024-06-30 00:00:00]
0.004600000102072954
0.012799999676644802
0.020600000396370888  #2023第3季度
0.020600000396370888  #2024第4季度
0.003800000064074993
而通过通达信看，2023的4个季度数据是0.0046, 0.0128，0.0206, 0.0270

**Comment by fasiondog** [comment]
> s = sm['sh600527'] e = FINANCE(0) q = Query(-5, ktype=Query.QUARTER) k = s.get_kdata(q) d = k.get_datetime_list() print(d) ret = e(k) for i in ret: print(i)
> 
> 返回： DatetimeList[2023-06-30 00:00:00, 2023-09-30 00:00:00, 2023-12-31 00:00:00, 2024-03-31 00:00:00, 2024-06-30 00:00:00] 0.004600000102072954 0.012799999676644802 0.020600000396370888 #2023第3季度 0.020600000396370888 #2023第4季度 0.003800000064074993 而通过通达信看，2023的4个季度数据是0.0046, 0.0128，0.0206, 0.0270

因为你取的K线是按季度取的，K线Bar对应的日期是季度开始时间，也就是 k[-1]的日期是 Datetime(2024,6,30,0,0,0,0,0)，这样是拿不到获取第四季度财报的，因为比较的日期是 6月30 日

**Comment by fasiondog** [comment]
如果你只是先获取财报，可以用 stock.get_history_finance 方法，然后自行根据日期去判断

**Comment by fasiondog** [comment]
k = s.get_kdata(Query(Datetime(20231231)))
e(k).plot()
![图片](https://github.com/fasiondog/hikyuu/assets/1145161/b4a25c3f-c1a2-4168-b0f6-6836ebe5d80c)
从这个图上也可以看出4季度的财报，4月12日左右才发布

**Comment by cheunjq** [comment]
> k = s.get_kdata(Query(Datetime(20231231))) e(k).plot() ![图片](https://private-user-images.githubusercontent.com/1145161/341371756-b4a25c3f-c1a2-4168-b0f6-6836ebe5d80c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4ODQ3ODcsIm5iZiI6MTcxODg4NDQ4NywicGF0aCI6Ii8xMTQ1MTYxLzM0MTM3MTc1Ni1iNGEyNWMzZi1jMWEyLTQxNjgtYjBmNi02ODM2ZWJlNWQ4MGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjBUMTE1NDQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzVlYWIzZGM4ZjI5ZmI3M2UxYjA4NDg1MDVhOTA5NmEyMDIxMGJmOWI2ZTJjOGIzNjI4NzUzYWFlNmYwOTYzNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.pyETUqwIUIElnsfs_L0HPFDSp0dPqmCZ_JsLm1F3S5U) 从这个图上也可以看出4季度的财报，4月12日左右才发布

谢谢大佬。但是还有点疑问，回测的时候，虽然2023年4季度的财报是2024年4月份才公布的，3季度的财报是2023年10月份公布的，但是当前这些数据都已经存到数据库了的，能不能通过算法修正。另外2024年1季度的数据是正确的，2023年4季度还在前面的，却只能用2023年3季度代替，有点奇怪！！！谢谢。。

**Comment by cheunjq** [comment]
表HistoryFinance里有file_date和report_date两个日期字段，算法是不是用了report_date这个字段，好像file_date才是正确的季度日期。
