### ISSUE TITLE
windows 10 通过python setup.py install 安装出错

### ISSUE THREAD

**Issue by Ultraman95** [fasiondog/hikyuu#28]
Python 版本 3.74
错误信息如下：
/*************************************************************************************************

C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winsock2.h(2662): error C2375: “WSACancelAsyncRequest”: 重定义；不同的链接
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winsock.h(936): note: 参见“WSACancelAsyncRequest”的声明
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winsock2.h(2680): error C2375: “WSAAsyncSelect”: 重定义；不同的链接
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winsock.h(938): note: 参见“WSAAsyncSelect”的声明
hikyuu_extern_libs\\pkg\\mysql.pkg\\inc\\release\\windows\\x64\mysql.h(752): error C2059: 语法错误:“}”
hikyuu_extern_libs\\pkg\\mysql.pkg\\inc\\release\\windows\\x64\mysql.h(752): error C2143: 语法错误: 缺少“;”(在“}”的前面)
E:\Experiment\C++\hikyuu\hikyuu_cpp\hikyuu\data_driver/base_info/mysql/MySQLBaseInfoDriver.h(20): error C2143: 语法错误: 缺少“;”(在“{”的前面)
E:\Experiment\C++\hikyuu\hikyuu_cpp\hikyuu\data_driver/base_info/mysql/MySQLBaseInfoDriver.h(20): error C2447: “{”: 缺少函数标题(是否是老式的形式表?)
hikyuu_cpp\hikyuu\StockManager.cpp(99): error C2065: “MySQLBaseInfoDriver”: 未声明的标识符
hikyuu_cpp\hikyuu\StockManager.cpp(99): error C2672: “std::make_shared”: 未找到匹配的重载函数
hikyuu_cpp\hikyuu\StockManager.cpp(99): error C2974: 'std::make_shared' : 模板 对于 '_Ty'是无效参数，应为类型
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.22.27905\include\memory(1607): note: 参见“std::make_shared”的声明

[ 38%]: compiling.release hikyuu_cpp\hikyuu\StockManager.cpp
[ 38%]: compiling.release hikyuu_cpp\hikyuu\Stock.cpp
[ 39%]: compiling.release hikyuu_cpp\hikyuu\trade_sys\moneymanager\imp\FixedCapitalMoneyManager.cpp
[ 39%]: compiling.release hikyuu_cpp\hikyuu\data_driver\KDataTempCsvDriver.cpp
error: StockManager.cpp
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared\ws2def.h(103): error C2220: 警告被视为错误 - 没有生成“object”文件
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared\ws2def.h(103): warning C4005: “AF_IPX”: 宏重定义
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winsock.h(457): note: 参见“AF_IPX”的前一个定义C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared\ws2def.h(147): warning C4005: “A
F_MAX”: 宏重定义
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winsock.h(476): note: 参见“AF_MAX”的前一个定义C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared\ws2def.h(185): warning C4005: “S
O_DONTLINGER”: 宏重定义
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winsock.h(399): note: 参见“SO_DONTLINGER”的前一个定义
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared\ws2def.h(238): error C2011: “sockaddr”:“struct”类型重定义
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winsock.h(1007): note: 参见“sockaddr”的声明
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared\ws2def.h(440): error C2143: 语法错误: 缺少“}”(在“常数”的前面)
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared\ws2def.h(440): error C2059: 语法错误:“常数”
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared\ws2def.h(494): error C2143: 语法错误: 缺少“;”(在“}”的前面)
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared\ws2def.h(494): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared\ws2def.h(494): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared\ws2def.h(575): warning C4005: “IN_CLASSA”: 宏重定义
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winsock.h(284): note: 参见“IN_CLASSA”的前一个定义
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared\ws2def.h(581): warning C4005: “IN_CLASSB”: 宏重定义
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winsock.h(290): note: 参见“IN_CLASSB”的前一个定义
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared\ws2def.h(587): warning C4005: “IN_CLASSC”: 宏重定义
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winsock.h(296): note: 参见“IN_CLASSC”的前一个定义
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared\ws2def.h(598): warning C4005: “INADDR_ANY”: 宏重定义
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winsock.h(301): note: 参见“INADDR_ANY”的前一个定义
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared\ws2def.h(600): warning C4005: “INADDR_BROADCAST”: 宏重定义
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winsock.h(303): note: 参见“INADDR_BROADCAST”的前一个定义
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared\ws2def.h(636): error C2011: “sockaddr_in”:“struct”类型重定义
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winsock.h(1011): note: 参见“sockaddr_in”的声明C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winsock2.h(136): error C2011: “fd_se
t”:“struct”类型重定义
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winsock.h(1019): note: 参见“fd_set”的声明

**Comment by Ultraman95** [comment]
我没有vs2017,只有vs2019

**Comment by Ultraman95** [comment]
是由于windows sdk的版本引起的吗？

**Comment by fasiondog** [comment]
不清楚，但之前有人用2019也是有问题

**Comment by Ultraman95** [comment]
我这边已经用windows sdk为10.0.17763这个版本还是不行

**Comment by Ultraman95** [comment]
你们成功编译的，用的windows sdk是哪个版本呢？
