### ISSUE TITLE
Mac上编译总是显示 mysql/mysql.h not found error

### ISSUE THREAD

**Issue by jamesmei** [fasiondog/hikyuu#29]
On Mac, I simply cannot run apt-get install libmysqlclient-dev, therefore when I run "python setup.py build", I get many errors about mysql.h such as:

error: hikyuu_cpp/hikyuu/utilities/db_connect/mysql/MySQLStatement.h:20:14: fatal error: 'mysql/mysql.h' file not found
    #include <mysql/mysql.h>
             ^~~~~~~~~~~~~~~
1 error generated.

This error makes sense to me, because on my Macbook, mysql.h is under /usr/local/mysql/include/ , not /usr/include/mysql. 

Then the question is: how to fix my build error?

Traditionally, in order to fix this error, I can simply add the path where mysql.h is located to "gcc -I [additional path]". I am not very familiar with how the build tool works in hikyuu, so it will be appreciated if someone can teach me how to add /usr/local/mysql/include in. Many thanks!

James

**Comment by fasiondog** [comment]
hikyuu_cpp/hikyuu/xmake.lua 中找mysql，修改下相关路径。（Mac下一般用brew，你用brew安装mysql应该也是可以的）
另外，mac的动态库路径一直没有搞定，即使能编译也仅能在编译的目录下跑。后面在改静态编译，但暂时boost.python和serialization还是没搞定

**Comment by jamesmei** [comment]
谢谢！这个问题解决了。我发现不能用最新的mysql，因为最新的mysql去掉了my_bool这个类型，build会break。我正在尝试下载mysql的老版本源代码，重新编译。

**Comment by walter211** [comment]
> 谢谢！这个问题解决了。我发现不能用最新的mysql，因为最新的mysql去掉了my_bool这个类型，build会break。我正在尝试下载mysql的老版本源代码，重新编译。

能更新下安装手册吗
