### ISSUE TITLE
使用use_draw_engine('echarts')后,plot和performance函数都报错

### ISSUE THREAD

**Issue by hoooou** [fasiondog/hikyuu#298]
使用use_draw_engine('echarts')后,plot函数和performance都报错
![image](https://github.com/user-attachments/assets/c3d10df3-f327-431b-b360-894413367cb3)
![image](https://github.com/user-attachments/assets/2ebd260c-b0d8-4ca5-859a-b1861981bc4b)

**Comment by fasiondog** [comment]
不清楚呢，目前主维护的只有 matplotlib, echarts很早以前升级接口不兼容，我就删除了，后来其他网友又贡献了一版新的，就合进来了。echarts和boktck自己有需要可以补充，欢迎贡献。sys.performance 是后来新增的并没有加入这两个引擎的。

**Comment by hoooou** [comment]
> 不清楚呢，目前主维护的只有 matplotlib, echarts很早以前升级接口不兼容，我就删除了，后来其他网友又贡献了一版新的，就合进来了。echarts和boktck自己有需要可以补充，欢迎贡献。sys.performance 是后来新增的并没有加入这两个引擎的。

好的
