### ISSUE TITLE
importdata以后c:\stock没有数据

### ISSUE THREAD

**Issue by luzzbob** [fasiondog/hikyuu#3]
您好，感谢开发了这款产品。我按照文档安装好，执行importdata时日志如下，但是运行测试30万本金的sz000001买入时提示stock为空。

日志：
^^^^^^^^^^^^^^^^^^^^^^^
c:\Python36\Lib\site-packages\hikyuu>importdata
目标数据库: c:\stock/stock.db
通达信数据源: c:\TdxW_HuaTai
sh_day  目标文件: c:\stock/sh_day.h5
sz_day  目标文件: c:\stock/sz_day.h5
sh_5min 目标文件: c:\stock/sh_5min.h5
sz_5min 目标文件: c:\stock/sz_5min.h5
sh_1min 目标文件: c:\stock/sh_1min.h5
sz_1min 目标文件: c:\stock/sz_1min.h5

从通达信导入股票代码表
0.109s

导入数据[sh_1min]: c:\TdxW_HuaTai/vipdoc/sh/minline
[==================================================] 100%
导入数量：0
17.347s

导入数据[sh_5min]: c:\TdxW_HuaTai/vipdoc/sh/fzline
[==================================================] 100%
导入数量：0
17.909s

导入数据[sh_day]: c:\TdxW_HuaTai/vipdoc/sh/lday
[==================================================] 100%
导入数量：0
16.957s

导入数据[sz_1min]: c:\TdxW_HuaTai/vipdoc/sz/minline
[==================================================] 100%
导入数量：0
18.689s

导入数据[sz_5min]: c:\TdxW_HuaTai/vipdoc/sz/fzline
[==================================================] 100%
导入数量：0
19.563s

导入数据[sz_day]: c:\TdxW_HuaTai/vipdoc/sz/lday
[==================================================] 100%
导入数量：0
18.876s

更新股票日期信息...
更新上证股票日期信息...
更新深证股票日期信息...
0.328s

导入上证权息信息: c:\stock/weight/shase/weight
[import_stock_weight] dir_path(c:\stock/weight/shase/weight) not exist!
0s

导入深证权息信息: c:\stock/weight/sznse/weight
[import_stock_weight] dir_path(c:\stock/weight/sznse/weight) not exist!
0.015s

总耗时：1.83093m 109.856s

Closing c:\stock/sz_day.h5...Closed!
Closing c:\stock/sz_5min.h5...Closed!
Closing c:\stock/sz_1min.h5...Closed!
Closing c:\stock/sh_day.h5...Closed!
Closing c:\stock/sh_5min.h5...Closed!
Closing c:\stock/sh_1min.h5...Closed!
Closing Sqlite3 database...Closed!

^^^^^^^^^^^^^^^^^^^^^^^
想请教一下：
1）怎么样才能获取到这份数据“沪市日线数据文件149M、深市日线数据文件184M、5分钟线数据各不到2G。”
2）为什么为会空

望赐教~

**Comment by fasiondog** [comment]
通达信有下载盘后数据吗？

**Comment by fasiondog** [comment]
删除数据文件，删除通达信已下载的数据，重新下载通达信数据，重新导入
