### ISSUE TITLE
fatal error: config.h: 没有那个文件或目录

### ISSUE THREAD

**Issue by dwdcth** [fasiondog/hikyuu#30]
rror: hikyuu_cpp/hikyuu/trade_sys/system/crt/../../environment/../../Log.h:12:10: fatal error: config.h: 没有那个文件或目录
   12 | #include "config.h"

使用git仓库里的最新代码，boost 1.72,  python 3.7，系统是ubuntu 20.04，已经安装说明配置好了boost

**Comment by fasiondog** [comment]
按帮助里的步骤编译，这是自动生成的

**Comment by dwdcth** [comment]
好的，清理缓存后好了
