### ISSUE TITLE
作者,你好, 我在macos下编译出现如下错误, 不知能否赐教

### ISSUE THREAD

**Issue by diorsx** [fasiondog/hikyuu#34]
current python version: 3.7
BOOST_ROOT: /Users/wood/Desktop/sofaware/hikyuu-master/boost_1_73_0
BOOST_LIB: /Users/wood/Desktop/sofaware/hikyuu-master/boost_1_73_0/stage/lib
checking for the architecture ... x86_64
checking for the Xcode directory ... /Applications/Xcode.app
checking for the SDK version of Xcode ... 10.15
checking for the Codesign Identity of Xcode ... no
error: bad argument #1 to 'parse' (string expected, got nil)
[100%]: build ok!
[ 80%]: compiling.release hikyuu_pywrap/trade_manage/_FundsRecord.cpp
[ 76%]: compiling.release hikyuu_pywrap/_KData.cpp
[ 81%]: compiling.release hikyuu_pywrap/trade_manage/_Performance.cpp
[ 77%]: compiling.release hikyuu_pywrap/indicator/_build_in.cpp
[ 78%]: compiling.release hikyuu_pywrap/trade_manage/_build_in.cpp
[ 77%]: compiling.release hikyuu_pywrap/indicator/_IndicatorImp.cpp
[ 80%]: compiling.release hikyuu_pywrap/trade_manage/_PositionRecord.cpp
[ 78%]: compiling.release hikyuu_pywrap/indicator/_Indicator.cpp
[ 81%]: compiling.release hikyuu_pywrap/trade_manage/_TradeCost.cpp
[ 76%]: compiling.release hikyuu_pywrap/trade_instance/_AmaInstance.cpp
[ 79%]: compiling.release hikyuu_pywrap/trade_manage/_BorrowRecord.cpp
[ 79%]: compiling.release hikyuu_pywrap/trade_manage/_CostRecord.cpp
error: hikyuu_pywrap/indicator/../pybind_utils.h:36:33: error: template argument for template type parameter must be a type; did you forget 'typename'?
        result[i] = py::extract<T::value_type>(pylist[i])();
                                ^
                                typename
/Users/wood/Desktop/sofaware/hikyuu-master/boost_1_73_0/boost/python/extract.hpp:125:17: note: template parameter is declared here
template <class T>
                ^
1 warning and 1 error generated.
warning: add_cxflags("-wd4251") is ignored, please pass `{force = true}` or call `set_policy("check.auto_ignore_flags", false)` if you want to set it.
current python version: 3.7
cp: hikyuu/*: No such file or directory

由于对c++不熟悉, 也不知其语法, 不知道从哪入手解决, 还望指点下.

**Comment by fasiondog** [comment]
已修改
