### ISSUE TITLE
使用通达信盘后数据导入数据库报错

### ISSUE THREAD

**Issue by redame** [fasiondog/hikyuu#38]
'gbk' codec can't decode byte 0xbb in position 7: incomplete multibyte sequence
导入完毕！
无法执行，
我想是这两个文件的问题，有一个太久未更新了，谢谢
tdx_to_h5.py
tdx_to_mysql.py

**Comment by fasiondog** [comment]
已修改，自己编译或者只拷贝hikyuu（python部分）试下

**Comment by fasiondog** [comment]
发了修复版本，可以安装更新下
