### ISSUE TITLE
api bug

### ISSUE THREAD

**Issue by XuWeiKiven** [fasiondog/hikyuu#40]
1、不能使用断点调试，会异常退出。
2、部分函数使用时，不能正常返回数据。
例如 
(1)blk = sm.get_block("指数板块", "上证380")
报出信息如下
2021-03-02 16:48:00.755 [HKU-I] - No such category (指数板块)! (QLBlockInfoDriver.cpp:24)

(2)
s = sm['sh000001']
k = s.get_kdata(Query(-100))  
k.plot()
没有画出图

**Comment by fasiondog** [comment]
k.plot 交互环境下自动画图，要设置matplotlib配置为交互模式，帮助里有。否则，每次需要自己手工调用下matplotlib的show()

**Comment by fasiondog** [comment]
![图片](https://user-images.githubusercontent.com/1145161/109667662-5627b900-7bab-11eb-975c-c2cd9722e61b.png)
我这没问题

**Comment by fasiondog** [comment]
单步调试，我这也没问题

**Comment by fasiondog** [comment]
你看看你是啥环境

**Comment by XuWeiKiven** [comment]
1、应该是加了这段from hikyuu.examples.examples_init import * 导致出现上述问题。
2、matplotlib显示图形时中文字体乱码的问题
（1）我是window10系统，按照说明文档修改，没有生效。
（2）window10 下用户目录“.matplotlib” 目录下 有fontlist-v330.json和tex.cache目录 ，删了也没效果。

**Comment by fasiondog** [comment]
> 
> 
> 1、应该是加了这段from hikyuu.examples.examples_init import * 导致出现上述问题。

这个有点老了
