### ISSUE TITLE
技术指标 RSI,KDJ

### ISSUE THREAD

**Issue by XuWeiKiven** [fasiondog/hikyuu#41]
运行代码 如下
   st = sm['SH000001']
   kd = st.get_kdata(Query(-100,ktype=Query.WEEK))
   r1,r2,r3 = RSI(kd)
报错在RSI里
![技术指标](https://user-images.githubusercontent.com/45867872/110730144-e70d2d00-825a-11eb-993a-0408f17b05b1.png)

**Comment by fasiondog** [comment]
你可以先CLOSE 改成 CLOSE()，稍后更新代码
