### ISSUE TITLE
DLL load failed: 动态链接库(DLL)初始化例程失败。

### ISSUE THREAD

**Issue by better319** [fasiondog/hikyuu#42]
![微信截图_20210522152017](https://user-images.githubusercontent.com/13842581/119218116-474d0480-bb11-11eb-8e11-f9a61a500a96.png)

**Comment by fasiondog** [comment]
这些报错的原因很有可能是你的CPU过老，或者规格属于服务器级别，如旧版本的志强系列CPU，这些原因都有可能造成pythone出现：
ImportError: DLL load failed: 动态链接库(DLL)初始化例程失败

**Comment by better319** [comment]
Initialize hikyuu_1.1.8_202102272126_x64_release ...
c:\anaconda3\lib\site-packages\numpy\__init__.py:140: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
  from . import _distributor_init
warning:can't import numpy or pandas lib,  you can't use method Inidicator.to_np() and to_df!
warning: can't import TA-Lib, will be ignored! You can fetch ta-lib from https://www.lfd.uci.edu/~gohlke/pythonlibs/#ta-lib



这个是不是也是一样的原因？

**Comment by better319** [comment]
![Uploading 360截图20210523165306752.jpg…]()

**Comment by better319** [comment]
![360截图20210523165306752](https://user-images.githubusercontent.com/13842581/119254160-661dca80-bbe7-11eb-8eed-c539318be39b.jpg)

**Comment by better319** [comment]
TA_Lib-0.4.20-cp37-cp37m-win_amd64
talib安装的是这个版本

**Comment by fasiondog** [comment]
> 
> 
> Initialize hikyuu_1.1.8_202102272126_x64_release ...
> c:\anaconda3\lib\site-packages\numpy__init__.py:140: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see [http://github.com/IntelPython/mkl-service](https://github.com/IntelPython/mkl-service)
> from . import _distributor_init
> warning:can't import numpy or pandas lib, you can't use method Inidicator.to_np() and to_df!
> warning: can't import TA-Lib, will be ignored! You can fetch ta-lib from https://www.lfd.uci.edu/~gohlke/pythonlibs/#ta-lib
> 
> 这个是不是也是一样的原因？

应该是吧，没有talib也没啥关系

**Comment by fasiondog** [comment]
> 
> 
> ![360截图20210523165306752](https://user-images.githubusercontent.com/13842581/119254160-661dca80-bbe7-11eb-8eed-c539318be39b.jpg)

看帮助，没有执行过数据导入

**Comment by better319** [comment]
估计还是这个cpu问题，用的是E5-2680v2

**Comment by better319** [comment]
通过卸载scipy,然后pip重新安装，以及离线安装包都不顶用，百度了还有的说重装pillow(但貌似需要这样都是老版本的python)

最后查到只需要装一个Visual C++ Redistributable for Visual Studio 2015，链接如下：

https://www.microsoft.com/en-us/download/details.aspx?id=48145

（运行结果提示imread 会被弃用，在Scipy 1.2.0之后 用 ‘imageio.imread’ 替代）用pip自动装的版本是1.2.1：

引用来源：https://stackoverflow.com/questions/53688759/module-not-found-when-using-scipy#
