### ISSUE TITLE
bokeh绘图问题

### ISSUE THREAD

**Issue by hahacaptain** [fasiondog/hikyuu#44]
bokeh_draw.py kplot方法：
 axes.add_tools(HoverTool(tooltips=[("index", "$index"), ('日期', get_date_format(k)), 
                                       ("开盘价", "@open{0.0000}"), ("最高价", "@high{0.0000}"), 
                                       ("最低价", "@low{0.0000}"),("收盘价", "@close{0.0000}"),
                                      ("成交金额", "@amount{0.0000}"), ("成交量", "@volume{0.0000}")],
                     formatters = { "datetime": "datetime"}))
formatters 少了一个@符号

get_date_format方法返回逻辑似乎写反了

**Comment by fasiondog** [comment]
已修改
