### ISSUE TITLE
hikyuu-1.1.8  build/test/install  提示 error: unknown target(sqlite3) for hikyuu.deps!  谢谢！

### ISSUE THREAD

**Issue by allen9mu** [fasiondog/hikyuu#46]
checking xmake ...
xmake v2.5.7+202110011221, A cross-platform build utility based on Lua
Copyright (C) 2015-present Ruki Wang, tboox.org, xmake.io
                         _
    __  ___ __  __  __ _| | ______
    \ \/ / |  \/  |/ _  | |/ / __ \
     >  <  | \__/ | /_| |   <  ___/
    /_/\_\_|_|  |_|\__ \|_|\_\____|
                         by ruki, xmake.io

    �  Manual: https://xmake.io/#/getting_started
    �  Donate: https://xmake.io/#/sponsor

current python version: 3.7
BOOST_ROOT: E:\AllInOne\Hikyuu\hikyuu-1.1.8/boost_1_77_0
BOOST_LIB: E:\AllInOne\Hikyuu\hikyuu-1.1.8/boost_1_77_0/stage/lib
checking for platform ... windows
checking for architecture ... x64
checking for Microsoft Visual Studio (x64) version ... 2019
**error: unknown target(sqlite3) for hikyuu.deps!**
checking for platform ... windows
checking for architecture ... x64
checking for Microsoft Visual Studio (x64) version ... 2019
error: unknown target(sqlite3) for hikyuu.deps!
checking for platform ... windows
checking for architecture ... x64
checking for Microsoft Visual Studio (x64) version ... 2019
**error: unknown target(sqlite3) for hikyuu.deps!**
checking for platform ... windows
checking for architecture ... x64
checking for Microsoft Visual Studio (x64) version ... 2019
**error: unknown target(sqlite3) for hikyuu.deps!**

我找了一下hikyuu_extern_lib这个目录下是空的

**Comment by waruqi** [comment]
git submodule update --init

**Comment by fasiondog** [comment]
git clone 时请加 --recursive 参数
