### ISSUE TITLE
除权计算不生效

### ISSUE THREAD

**Issue by pttpzp** [fasiondog/hikyuu#52]
**问题描述：**
    测试策略中发现结果异常，回查K线数据，发现前复权计算似乎没有生效，经绘制K线对比，确认数据有问题。

**重现方法：**
   股票代码：_sh603392_

ipynb代码
```
%matplotlib inline
%time from hikyuu.interactive import *

s = sm['sh603392']

# 查看权息信息
ws = sm['sh603392'].get_weight()
for w in ws:
    print(w)
```

```
#查询股票最后200个交易日K线数据，不复权
k = s.get_kdata(Query(-200))
k.plot()
```
![0E~$J3115FF6OQY6TY{AQVE](https://user-images.githubusercontent.com/3377482/148320586-efd2c56b-2146-47ec-abba-11dc2188ee34.png)

```
#查询股票最后200个交易日K线数据，前向复权
k = s.get_kdata(Query(-200, recover_type=Query.FORWARD))
k.plot()
```
![F@MZN1Z82}M@Q9DX W{@ GY](https://user-images.githubusercontent.com/3377482/148320615-3f61a8ee-01b8-432b-9991-aa256aa98e06.png)
```
#查询股票最后200个交易日K线数据，后向复权
k = s.get_kdata(Query(-200, recover_type=Query.BACKWARD))
k.plot()
```
![NSC{5~A16SU~5O3VEQ7%}BR](https://user-images.githubusercontent.com/3377482/148320738-e3884116-d5e3-4bdf-8683-0f8453c28a43.png)

**Comment by fasiondog** [comment]
更换使用通达信的权息数据后引入的问题
