### ISSUE TITLE
win10下图形界面无法导入

### ISSUE THREAD

**Issue by zylikedream** [fasiondog/hikyuu#59]
hikyuutdx 图形界面无法导入  控制台日志无任何报错
![image](https://user-images.githubusercontent.com/7788749/154633257-298f82f8-3ddf-425e-8bd0-146729e8a5d2.png)

但是使用importdata可以导入
![image](https://user-images.githubusercontent.com/7788749/154624368-f3207b65-0fc0-4e62-a8f1-cc0d47631370.png)

**Comment by fasiondog** [comment]
多半是PyQt5的问题，重装PyQt试下吧

**Comment by yrwy** [comment]
> 

应该不是pyqt的问题，报错如下：

`Process Process-1:
Traceback (most recent call last):
  File "C:\Miniconda3\envs\py38\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Miniconda3\envs\py38\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Miniconda3\envs\py38\lib\site-packages\hikyuu\gui\data\ImportWeightToSqliteTask.py", line 51, in __call__
    capture_multiprocess_all_logger(self.log_queue)
  File "C:\Miniconda3\envs\py38\lib\site-packages\hikyuu\util\mylog.py", line 203, in capture_multiprocess_all_logger
    qh = logging.handlers.QueueHandler(queue)
AttributeError: module 'logging' has no attribute 'handlers'
Quit Hikyuu system!
`

用pycharm 或者是用python xxxx.py启动都不会出错

**Comment by fasiondog** [comment]
> 

那估计应该是 python 版本有问题，这个错误提示的是 logging 模块没有 handlers 属性

**Comment by fasiondog** [comment]
> > 
> 
> 应该不是pyqt的问题，报错如下：
> 
> `Process Process-1: Traceback (most recent call last): File "C:\Miniconda3\envs\py38\lib\multiprocessing\process.py", line 315, in _bootstrap self.run() File "C:\Miniconda3\envs\py38\lib\multiprocessing\process.py", line 108, in run self._target(*self._args, **self._kwargs) File "C:\Miniconda3\envs\py38\lib\site-packages\hikyuu\gui\data\ImportWeightToSqliteTask.py", line 51, in __call__ capture_multiprocess_all_logger(self.log_queue) File "C:\Miniconda3\envs\py38\lib\site-packages\hikyuu\util\mylog.py", line 203, in capture_multiprocess_all_logger qh = logging.handlers.QueueHandler(queue) AttributeError: module 'logging' has no attribute 'handlers' Quit Hikyuu system! `
> 
> 用pycharm 或者是用python xxxx.py启动都不会出错

python 的版本是多少？这个像是 python 的 logging 库缺少 handlers

**Comment by yrwy** [comment]
> 
miniconda 最新版的 py3.8 
所有依赖都是通过conda install xxx 进行的
查了下stackoverflow 好像也是说logging的问题 说是py39 310都没有问题

**Comment by szy2k** [comment]
请问你的问题解决了吗?

**Comment by yrwy** [comment]
直接运行HikyuuTDX.py这个文件就可以了

**Comment by xhulife** [comment]
HDF5的版本是否正确，我安装了hdf5 1.12.0版本之后，正确导入数据
conda install -c anaconda hdf5=1.12.0
