### ISSUE TITLE
请问复权算法用的是通达信类型的还是WIND类型？

### ISSUE THREAD

**Issue by solensolen** [fasiondog/hikyuu#6]
因为通达信的复权算法会导致出现负数价格。
另外，分钟线的复权现在是否支持？

**Comment by fasiondog** [comment]
只支持日线复权。根据百度的算法计算的，应该偏通达信吧，有没有负数没注意。

**Comment by solensolen** [comment]
好的。
wind对复权有一个具体的说明，它们采用基于收益率调整的复权算法，不会出现负值
http://180.96.8.19/windnet/Bulletin/express/fqsf.pdf
复权出现负值的话，统计时有点小麻烦。不过没事，我根据pytdx它们搞定的函数可以本地处理好之后输入。
权息数据tdx本地gbbq文件和pytdx接口从网络拿，两者数据结构不太一样，但内容应该一致。
