### ISSUE TITLE
hikyuu_cpp/hikyuu/global/agent/spot_generated.h:157:12: error: no matching member function for call to 'VerifyField'

### ISSUE THREAD

**Issue by wjlxyz** [fasiondog/hikyuu#66]
mac上build失败，报错如下

[ 58%]: compiling.release hikyuu_cpp/hikyuu/utilities/Parameter.cpp
error: hikyuu_cpp/hikyuu/global/agent/spot_generated.h:156:12: error: no matching member function for call to 'VerifyField'
           VerifyField<double>(verifier, VT_YESTERDAY_CLOSE) &&
           ^~~~~~~~~~~~~~~~~~~
/usr/local/include/flatbuffers/table.h:115:8: note: candidate function template not viable: requires 3 arguments, but 2 were provided
  bool VerifyField(const Verifier &verifier, voffset_t field,
       ^
In file included from hikyuu_cpp/hikyuu/GlobalInitializer.cpp:22:
In file included from hikyuu_cpp/hikyuu/global/GlobalSpotAgent.h:8:
In file included from hikyuu_cpp/hikyuu/global/agent/SpotAgent.h:12:
hikyuu_cpp/hikyuu/global/agent/spot_generated.h:157:12: error: no matching member function for call to 'VerifyField'
           VerifyField<double>(verifier, VT_OPEN) &&
           ^~~~~~~~~~~~~~~~~~~
/usr/local/include/flatbuffers/table.h:115:8: note: candidate function template not viable: requires 3 arguments, but 2 were provided
  bool VerifyField(const Verifier &verifier, voffset_t field,
       ^
In file included from hikyuu_cpp/hikyuu/GlobalInitializer.cpp:22:
In file included from hikyuu_cpp/hikyuu/global/GlobalSpotAgent.h:8:
warning: target(hikyuu).add_linkdirs("/Users/wangjinlong/workspace/hikyuu/boost_1_79_0/stage/lib") path not found at ./xmake.lua:78
[ 44%]: compiling.release hikyuu_cpp/hikyuu/GlobalInitializer.cpp
[ 44%]: compiling.release hikyuu_cpp/hikyuu/utilities/Parameter.cpp
error: hikyuu_cpp/hikyuu/global/agent/spot_generated.h:156:12: error: no matching member function for call to 'VerifyField'
           VerifyField<double>(verifier, VT_YESTERDAY_CLOSE) &&
           ^~~~~~~~~~~~~~~~~~~
/usr/local/include/flatbuffers/table.h:115:8: note: candidate function template not viable: requires 3 arguments, but 2 were provided
  bool VerifyField(const Verifier &verifier, voffset_t field,
       ^
In file included from hikyuu_cpp/hikyuu/GlobalInitializer.cpp:22:
In file included from hikyuu_cpp/hikyuu/global/GlobalSpotAgent.h:8:
In file included from hikyuu_cpp/hikyuu/global/agent/SpotAgent.h:12:
hikyuu_cpp/hikyuu/global/agent/spot_generated.h:157:12: error: no matching member function for call to 'VerifyField'
           VerifyField<double>(verifier, VT_OPEN) &&
           ^~~~~~~~~~~~~~~~~~~
/usr/local/include/flatbuffers/table.h:115:8: note: candidate function template not viable: requires 3 arguments, but 2 were provided
  bool VerifyField(const Verifier &verifier, voffset_t field,
       ^
In file included from hikyuu_cpp/hikyuu/GlobalInitializer.cpp:22:
In file included from hikyuu_cpp/hikyuu/global/GlobalSpotAgent.h:8:

**Comment by wjlxyz** [comment]
看了flatbuffer里的这个方法，确实是三个参数，
template<typename T>
  bool VerifyField(const uint8_t *base, voffset_t elem_off,
                   size_t align) const {
    auto f = static_cast<size_t>(base - buf_) + elem_off;
    return VerifyAlignment(f, align) && Verify(f, sizeof(T));
  }

**Comment by wjlxyz** [comment]
或者能说一下需要的这些库的版本吗

**Comment by swaiyu** [comment]
我也遇到这个问题了，有办法怎么解决吗？

**Comment by fasiondog** [comment]
或者先用 xmake 分支，后面有空再升级。python里的flatbuffer版本也要指定。

**Comment by swaiyu** [comment]
好的，非常感谢，我的问题解决了，直接参考tensorflowlite官网的方法，新建一个build文件夹，用cmake ../tensorflow_src/tensorflow/lite 命令，可以直接下载生成匹配版本的flatbuffer库，详细的可以看官方网页https://tensorflow.google.cn/lite/guide/build_cmake
