### ISSUE TITLE
能否方便给一个外部调用刷新sm preloading缓存的方案

### ISSUE THREAD

**Issue by stefangui** [fasiondog/hikyuu#69]
比如一个常驻内存的py脚本，在开始的时候只调用hikyuu库一次，然后如果有后端的抓取程序更新sqlite或者mysql，我这边的sm取不到最新的缓存数据，我看你有StockManager.reload()方法，但是我外部调用不到，能否给一个外部调用刷新缓存的方式？谢谢

**Comment by fasiondog** [comment]
Stock 的 realtime_update 方法，直接将 KRecord 更新进去，已经有了
