### ISSUE TITLE
关于图形界面导入数据问题，1.2.0-1.2.4版本都不能正常导入数据

### ISSUE THREAD

**Issue by 280185386** [fasiondog/hikyuu#71]
关于图形界面导入数据问题，1.2.0-1.2.4版本都不能正常导入数据，   1.1.9版本可以正常导入数据

**Comment by 280185386** [comment]
用的ａｎａｃｏｎｄａ　２０２０－０５版本

**Comment by 280185386** [comment]
上边写错了，用的Anaconda3-2022.05-Windows-x86_64.exe这个版本

**Comment by fasiondog** [comment]
https://github.com/fasiondog/hikyuu/issues/59
