### ISSUE TITLE
增加回测买卖价格配置

### ISSUE THREAD

**Issue by yehonghao** [fasiondog/hikyuu#73]
目前信号可以做到设置延迟买入，但卖出也同步延迟一天了。期望可以自由设置 买入 卖出 是否延迟，买入，卖出使用开盘价，或是收盘价

**Comment by fasiondog** [comment]
改完了，master分支，你可以试下
https://github.com/fasiondog/hikyuu/commit/58bca1b98f70c7730a0327b2b0f4cf056a59a992

**Comment by fasiondog** [comment]
> 

你可以尝试通自定义移滑价差算法去计算实际买入、卖出的价格，还能比较这样和普通的仿真直接的差异

**Comment by fasiondog** [comment]
![图片](https://user-images.githubusercontent.com/1145161/202508806-3bdf6cbc-329c-4fd2-a6c4-db142ed38698.png)
类似这样
