### ISSUE TITLE
请问支持策略持久化/跟踪吗？

### ISSUE THREAD

**Issue by Daic115** [fasiondog/hikyuu#74]
你好，想请问下这个项目是否支持策略的持久化与跟踪？ 
比如：
> 对多个已经回测完成的策略，在每日数据更新后，增量运行策略，得到最新的绩效。

**Comment by fasiondog** [comment]
严格意义上是不能，虽然你可用用pickle保存并导入，但导入的是上次计算的结果。重新计算时，如果Query没有设置最后日期，那么是会自动取最新的数据进行重算，但不是之计算新加的那一条，而是重头到最新的一起重算。

**Comment by Daic115** [comment]
好的我回去试试 谢谢！
