### ISSUE TITLE
bokeh库更新了 删掉了Figure 导致Hikyuu运行不了

### ISSUE THREAD

**Issue by cyoki** [fasiondog/hikyuu#84]
ImportError: cannot import name 'Figure' from 'bokeh.plotting' (bokeh\plotting\__init__.py)
可能需要更新一下这个函数 因为你有一个 from bokeh.plotting import Figure, figure, ColumnDataSource
默认安装的bokeh就是最新版

**Comment by du-hyper** [comment]
对的，或者Figure指定一下版本

**Comment by fasiondog** [comment]
已处理
