### ISSUE TITLE
Ubuntu环境编译报错

### ISSUE THREAD

**Issue by samsonsheng** [fasiondog/hikyuu#85]
Ubuntu环境下编译就报错了，boost库路径是手动设置的环境变量，是正确的。
BOOST_ROOT: /home/ubuntu/money/hikyuu/boost_1_69_0/
BOOST_LIB: /home/ubuntu/money/hikyuu/boost_1_69_0/libs/

错误如下：

`(hikyuu) python setup.py build
checking xmake ...
xmake v2.7.6+20230223, A cross-platform build utility based on Lua
Copyright (C) 2015-present Ruki Wang, tboox.org, xmake.io
                         _
    __  ___ __  __  __ _| | ______
    \ \/ / |  \/  |/ _  | |/ / __ \
     >  <  | \__/ | /_| |   <  ___/
    /_/\_\_|_|  |_|\__ \|_|\_\____|
                         by ruki, xmake.io

    👉  Manual: https://xmake.io/#/getting_started
    🙏  Donate: https://xmake.io/#/sponsor

  ╔════════════════════════════════════════════════════════════════════════════╗
  ║ A new version of xmake is available!                                       ║
  ║                                                                            ║
  ║ To update to the latest version v2.7.7, run "xmake update".                ║
  ╚════════════════════════════════════════════════════════════════════════════╝

current python version: 3.9
BOOST_ROOT: /home/ubuntu/money/hikyuu/boost_1_69_0/
BOOST_LIB: /home/ubuntu/money/hikyuu/boost_1_69_0/libs/
[  1%]: cache compiling.release hikyuu_cpp/hikyuu/global/agent/SpotAgent.cpp
[  0%]: cache compiling.release hikyuu_cpp/hikyuu/GlobalInitializer.cpp
error: hikyuu_cpp/hikyuu/global/agent/spot_generated.h:156:31: error: no matching function for call to ‘hikyuu::flat::Spot::VerifyField<double>(flatbuffers::Verifier&, hikyuu::flat::Spot::FlatBuffersVTableOffset) const’
  156 |            VerifyField<double>(verifier, VT_YESTERDAY_CLOSE) &&
      |            ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/ubuntu/.xmake/packages/f/flatbuffers/v23.1.21/456fc5cdc03645c69e6ca2dda977b56f/include/flatbuffers/flatbuffer_builder.h:33,
                 from /home/ubuntu/.xmake/packages/f/flatbuffers/v23.1.21/456fc5cdc03645c69e6ca2dda977b56f/include/flatbuffers/flatbuffers.h:29,
                 from hikyuu_cpp/hikyuu/global/agent/spot_generated.h:7,
                 from hikyuu_cpp/hikyuu/global/agent/SpotAgent.h:12,
                 from hikyuu_cpp/hikyuu/global/agent/SpotAgent.cpp:11:
/home/ubuntu/.xmake/packages/f/flatbuffers/v23.1.21/456fc5cdc03645c69e6ca2dda977b56f/include/flatbuffers/table.h:115:8: note: candidate: ‘bool flatbuffers::Table::VerifyField(const flatbuffers::Verifier&, flatbuffers::voffset_t, size_t) const [with T = double; flatbuffers::voffset_t = short unsigned int; size_t = long unsigned int]’
  115 |   bool VerifyField(const Verifier &verifier, voffset_t field,
      |        ^~~~~~~~~~~
/home/ubuntu/.xmake/packages/f/flatbuffers/v23.1.21/456fc5cdc03645c69e6ca2dda977b56f/include/flatbuffers/table.h:115:8: note:   candidate expects 3 arguments, 2 provided
In file included from hikyuu_cpp/hikyuu/global/agent/SpotAgent.h:12,
                 from hikyuu_cpp/hikyuu/global/agent/SpotAgent.cpp:11:
hikyuu_cpp/hikyuu/global/agent/spot_generated.h:157:31: error: no matching function for call to ‘hikyuu::flat::Spot::VerifyField<double>(flatbuffers::Verifier&, hikyuu::flat::Spot::FlatBuffersVTableOffset) const’
  157 |            VerifyField<double>(verifier, VT_OPEN) &&
      |            ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
  > in hikyuu_cpp/hikyuu/global/agent/SpotAgent.cpp
[  1%]: cache compiling.release hikyuu_cpp/hikyuu/global/agent/SpotAgent.cpp
[  0%]: cache compiling.release hikyuu_cpp/hikyuu/GlobalInitializer.cpp
error: hikyuu_cpp/hikyuu/global/agent/spot_generated.h:156:31: error: no matching function for call to ‘hikyuu::flat::Spot::VerifyField<double>(flatbuffers::Verifier&, hikyuu::flat::Spot::FlatBuffersVTableOffset) const’
  156 |            VerifyField<double>(verifier, VT_YESTERDAY_CLOSE) &&
      |            ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/ubuntu/.xmake/packages/f/flatbuffers/v23.1.21/456fc5cdc03645c69e6ca2dda977b56f/include/flatbuffers/flatbuffer_builder.h:33,
                 from /home/ubuntu/.xmake/packages/f/flatbuffers/v23.1.21/456fc5cdc03645c69e6ca2dda977b56f/include/flatbuffers/flatbuffers.h:29,
                 from hikyuu_cpp/hikyuu/global/agent/spot_generated.h:7,
                 from hikyuu_cpp/hikyuu/global/agent/SpotAgent.h:12,
                 from hikyuu_cpp/hikyuu/global/agent/SpotAgent.cpp:11:
/home/ubuntu/.xmake/packages/f/flatbuffers/v23.1.21/456fc5cdc03645c69e6ca2dda977b56f/include/flatbuffers/table.h:115:8: note: candidate: ‘bool flatbuffers::Table::VerifyField(const flatbuffers::Verifier&, flatbuffers::voffset_t, size_t) const [with T = double; flatbuffers::voffset_t = short unsigned int; size_t = long unsigned int]’
  115 |   bool VerifyField(const Verifier &verifier, voffset_t field,
      |        ^~~~~~~~~~~
/home/ubuntu/.xmake/packages/f/flatbuffers/v23.1.21/456fc5cdc03645c69e6ca2dda977b56f/include/flatbuffers/table.h:115:8: note:   candidate expects 3 arguments, 2 provided
In file included from hikyuu_cpp/hikyuu/global/agent/SpotAgent.h:12,
                 from hikyuu_cpp/hikyuu/global/agent/SpotAgent.cpp:11:
hikyuu_cpp/hikyuu/global/agent/spot_generated.h:157:31: error: no matching function for call to ‘hikyuu::flat::Spot::VerifyField<double>(flatbuffers::Verifier&, hikyuu::flat::Spot::FlatBuffersVTableOffset) const’
  157 |            VerifyField<double>(verifier, VT_OPEN) &&
      |            ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
  > in hikyuu_cpp/hikyuu/global/agent/SpotAgent.cpp`

**Comment by samsonsheng** [comment]
请问项目有没有交流群啊

**Comment by YuLoveXia** [comment]
我刚处理过，在 顶成 xmake.lua 目录里找到 flatbuffers   指定版本为 v2.0.5  就可以了

**Comment by YuLoveXia** [comment]
q :  114910869

**Comment by fasiondog** [comment]
现在可以了
