### ISSUE TITLE
ubuntu怎么初始化配置

### ISSUE THREAD

**Issue by allenwang2022** [fasiondog/hikyuu#88]

**Comment by allenwang2022** [comment]
![image](https://user-images.githubusercontent.com/96903696/227751391-e6964a87-8674-4e6d-8f2f-6f9cd75d3c10.png)
这个里面的初始化配置

**Comment by fasiondog** [comment]
你可以在windows下执行 hikyuuTdx， 然后从windows下用户目录里的 .hikyuu 目录下找到 hikyuu.ini 和 importdata-gui.ini 文件，拷贝过去，然后手工把里面的相关目录名改下
