### ISSUE TITLE
是不是不支持3.10啊 为什么运行 from hikyuu.interactive import * 会出现NoSectionError: No section: 'hikyuu'

### ISSUE THREAD

**Issue by cyoki** [fasiondog/hikyuu#94]
---------------------------------------------------------------------------
NoSectionError                            Traceback (most recent call last)
File <timed exec>:1

File ~\scoop\apps\python310\current\lib\site-packages\hikyuu\interactive.py:96
     94 ini.read(config_file)
     95 hku_param = Parameter()
---> 96 hku_param["tmpdir"] = ini.get('hikyuu', 'tmpdir')
     97 hku_param["datadir"] = ini.get('hikyuu', 'datadir')
     98 if ini.has_option('hikyuu', 'logger'):

File ~\scoop\apps\python310\current\lib\configparser.py:783, in RawConfigParser.get(self, section, option, raw, vars, fallback)
    768 """Get an option value for a given section.
    769 
    770 If `vars` is provided, it must be a dictionary. The option is looked up
   (...)
    780 The section DEFAULT is special.
    781 """
    782 try:
--> 783     d = self._unify_values(section, vars)
    784 except NoSectionError:
    785     if fallback is _UNSET:

File ~\scoop\apps\python310\current\lib\configparser.py:1154, in RawConfigParser._unify_values(self, section, vars)
   1152 except KeyError:
   1153     if section != self.default_section:
-> 1154         raise NoSectionError(section) from None
   1155 # Update with the entry specific variables
   1156 vardict = {}

NoSectionError: No section: 'hikyuu'

**Comment by fasiondog** [comment]
没执行 hikyuutdx 导入数据吧

**Comment by cyoki** [comment]
> 

执行了啊 我先导入了数据啊 然后下载完之后才运行的

**Comment by YuanJiaShuai** [comment]
记录一下，也遇到3.10 报错 NoSectionError: No section: 'hikyuu'，选择Python 3.12 环境可以正常执行

**Comment by fasiondog** [comment]
> 记录一下，也遇到3.10 报错 NoSectionError: No section: 'hikyuu'，选择Python 3.12 环境可以正常执行

不同的环境要install
