### ISSUE TITLE
保存配置信息失败

### ISSUE THREAD

**Issue by cyoki** [fasiondog/hikyuu#96]
![image](https://github.com/fasiondog/hikyuu/assets/17739163/4095f78d-30ed-4ed9-8270-88c02d8d5f31)

但是直接用importdata.py可以导入 但是因为保存信息失败，导致hikyuu.ini是空的
导致 NoSectionError: No section: **'hikyuu'**

NoSectionError                            Traceback (most recent call last)
Cell In[1], line 1
----> 1 from hikyuu.interactive import *

File ~\scoop\apps\python310\current\lib\site-packages\hikyuu\interactive.py:96
     94 ini.read(config_file)
     95 hku_param = Parameter()
---> 96 hku_param["tmpdir"] = ini.get('hikyuu', 'tmpdir')
     97 hku_param["datadir"] = ini.get('hikyuu', 'datadir')
     98 if ini.has_option('hikyuu', 'logger'):

我把HikyuuTDX.py 第104行改成UTF-8编码之后能运行，但是你的注释说不能用UTF-8

然后这样得到文件再运行 又出现新的错误 

---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
Cell In[1], line 1
----> 1 from hikyuu.interactive import *

File ~\scoop\apps\python310\current\lib\site-packages\hikyuu\interactive.py:94
     91         raise Exception("未找到配置文件，请先使用数据导入工具导入数据（将自动生成配置文件）！！!")
     93 ini = configparser.ConfigParser()
---> 94 ini.read(config_file)
     95 hku_param = Parameter()
     96 hku_param["tmpdir"] = ini.get('hikyuu', 'tmpdir')

File ~\scoop\apps\python310\current\lib\configparser.py:699, in RawConfigParser.read(self, filenames, encoding)
    697 try:
    698     with open(filename, encoding=encoding) as fp:
--> 699         self._read(fp, filename)
    700 except OSError:
    701     continue

File ~\scoop\apps\python310\current\lib\configparser.py:1022, in RawConfigParser._read(self, fp, fpname)
   1020 indent_level = 0
   1021 e = None                              # None, or an exception
-> 1022 for lineno, line in enumerate(fp, start=1):
   1023     comment_start = sys.maxsize
   1024     # strip inline comments

File ~\scoop\apps\python310\current\lib\encodings\cp1252.py:23, in IncrementalDecoder.decode(self, input, final)
     22 def decode(self, input, final=False):
---> 23     return codecs.charmap_decode(input,self.errors,decoding_table)[0]

UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 221: character maps to <undefined>

**Comment by fasiondog** [comment]
是不是用了中文路径？Qt支持不好

**Comment by cyoki** [comment]
> 

我明白了 可能是因为我是纯英文系统 对中文的支持不好。有什么改进的措施吗？

**Comment by fasiondog** [comment]
没有，local设置成utf8的试试

**Comment by cyoki** [comment]
> 没有，local设置成utf8的试试

我找到方法了 设置环境变量

PYTHONIOENCODING = UTF-8
PYTHONUTF8 = 1
