### ISSUE TITLE
Stock类的get_market_value函数似乎返回的是当天的收盘价

### ISSUE THREAD

**Issue by kbugstar** [fasiondog/hikyuu#98]
sm['sh601919'].get_market_value(Datetime(20230616), Query.DAY)
10.790000000000001
是我下载的数据不对吗？

**Comment by fasiondog** [comment]
不是，而是这个值就是当前所能获取的最后的收盘价

**Comment by fasiondog** [comment]
获取指定日期时刻的市值，即小于等于指定日期的最后一条记录的收盘价

**Comment by kbugstar** [comment]
> 不是，而是这个值就是当前所能获取的最后的收盘价

仔细看了一下这个函数的说明，结果是对的，就是函数的名字很有误导性
